### PR TITLE
Codegen stuff (WIP)

### PR DESCRIPTION
**Pull request by sconybeare**

### CODE REVIEW

**Comment by zenhack** [comment]
Ack, wish I'd been less sloppy about leaving these around -- I've been working on read support in Schema.CapNProto.Reader, so this bit is a little out of date.

There's a big problem with the aproach taken here, which is that it requires actually parsing the whole message. The notion with capnproto is to avoid having to do a big serialization step, so using simple haskell datatypes that mirror the structure of the schema is unfortunately a no-go; you'd either have to parse the whole thing up front, or do it lazily, in which case you run into the possibility of getting an exception asynchronously when you evaluate the bit that has some kind of invalid data/schema violation/hits a traversal limit.

Have a look at the the approach taken by Data.CapNProto.Untyped, and the wrappers I've been working on with Language.CapNProto.TH and Schema.CapNProto.Reader

**Comment by zenhack** [comment]
Since I missed you on IRC:

```
(15:17:18) sconybeare: I see
(15:17:57) sconybeare: I was only intending to use that stuff to parse a capnproto schema file
(15:19:11) sconybeare: and then generate the types of the haskell bindings for the protocol
```

Doing the TH approach has a handful of advantages:

* We can use the same TH helpers as part of our code generation routines, so it's not throwaway work that we'll just use for bootstrapping. Once we've got them in place, we can just walk the tree that `capnp compile` hands us and call the wrappers we've already written. Manually parsing the untyped message into the standard haskell adts will be at least as much as much work, and then we'll have to actually write stuff to do codegen from the adts.
* It will force us to actually dogfood the reader API, so we'll see pain points with it early on.

**Comment by taktoa** [comment]
@zenhack Are you sure we should use TH? There are a lot of (good-to-have) predicates which are true of Haskell files without TH, but are not true of Haskell files with TH, and there's no way to partially-evaluate out all the TH from a Haskell file. For example, IIRC, using TH forces any user to abandon all hope of Safe Haskell compliance (not that many people do that).

I think that it would probably be better to use `ghc-exactprint` to generate actual Haskell code, and distribute a program that can be used in a Cabal preprocessing step. That's roughly the approach used in [proto3-suite](https://github.com/awakesecurity/proto3-suite), which is used by Awake Security in production. Oh, also, TH is pretty slow to compile compared to plain old Haskell files.

**Comment by zenhack** [comment]
@taktoa, I spent some time thinking about, it, and am inclined to stick with the TH approach. The types define in the exactprint API seem overly complex for what we actually want -- they look like they're focused on high-quality pretty-printing, which we really don't care about -- and in any case working directly with Asts ends up being really verbose; the quasi-quote notation available with TH makes it *much* nicer to work with.

We can write a program like you suggest using [pprint][1]; we don't need the user to use TH directly in their packages. I'd been thinking this might be a good approach anyway, since the way I'm doing this there are going to be multiple `.hs` files for each `.capnp` file.

[1]: https://hackage.haskell.org/package/template-haskell-2.12.0.0/docs/Language-Haskell-TH-Ppr.html#v:pprint

**Comment by taktoa** [comment]
That sounds fine, though I am somewhat concerned about maintainability; the TH interface changes often and drastically, whereas an ad-hoc pretty-printer for the subset of Haskell we need would probably not need to change much (and if you're worried about the pretty-printer accidentally printing invalid Haskell, we could roundtrip it with ghc-exactprint or haskell-src-exts before we print it).

**Comment by sconybeare** [comment]
I closed this since it seems like it's no longer relevant, and I think it would be hard for me to work more on this issue without duplicating work.

**Comment by zenhack** [comment]
Yeah, good call.

Quoting Sebastian Conybeare (2017-09-19 20:12:53)

>    I closed this since it seems like it's no longer relevant, and I think
>    it would be hard for me to work more on this issue without duplicating
>    work.

**Pull request closed without merging**
